apiVersion: v1
kind: Pod
metadata:
  name: person-svc
spec:
  containers:
  - name: person-svc
    image: servantscode/person-svc
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: "200Mi"
    env:
    - name: ES_JAVA_OPTS 
      value: "-Xmx128m -Xms128m"
